# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-pipeline

on:
  push:
    branches:
      - main

jobs:

  CI_Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Remove old env
        run: rm -f .env

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_VITE_WS_URI: ${{ secrets.DEV_WS_URI }}
          ENV_VITE_FE_URL: ${{ secrets.DEV_FE_URL }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/gbp_fe:dev

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gbp_fe:dev